# NHIỆM VỤ 1: SỬ DỤNG DỮ LIỆU COVID-19

In [18]:

# pip install pandas numpy scipy

import pandas as pd
import numpy as np
from scipy import stats

In [19]:
url = "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv"
df = pd.read_csv(url)

# Xem cấu trúc dữ liệu
print(df.shape)
print(df.columns)
df.head()

(429435, 67)
Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population_density', 'median_age', 'aged_65_older', 'aged_70_older',
       'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate',
       'diabetes_prevalence', 'female_smokers', 'male_smokers',
       'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'population',
       'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative',
       'excess_mortality', 'excess_mortality_cumulative_per_million'],
      dtype='object')

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN

In [20]:
# Lọc bỏ các giá trị NaN
data = df['total_cases'].dropna()

print("Số lượng quan sát:", len(data))
print("5 giá trị đầu:\n", data.head())

Số lượng quan sát: 411804
5 giá trị đầu:
 0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: total_cases, dtype: float64

In [24]:
# Mean (trung bình)
mean_val = np.mean(data)

# Median (trung vị)
median_val = np.median(data)

# Mode (giá trị xuất hiện nhiều nhất)
mode_val = stats.mode(data, keepdims=True)[0][0]

# Variance (phương sai)
variance_val = np.var(data)

# Standard deviation (độ lệch chuẩn)
std_val = np.std(data)

# Range (khoảng)
range_val = np.max(data) - np.min(data)

# Percentile (ví dụ: 25th, 50th, 75th)
percentiles = np.percentile(data, [25, 50, 75])

# Quartiles
Q1, Q2, Q3 = np.percentile(data, [25, 50, 75])

# IQR (interquartile range)
IQR = Q3 - Q1

# In kết quả
print("Thống kê dữ liệu COVID:")
print(f"Mean: {mean_val:.2f}")
print(f"Median: {median_val:.2f}")
print(f"Mode: {mode_val:.2f}")
print(f"Variance: {variance_val:.2f}")
print(f"Standard Deviation: {std_val:.2f}")
print(f"Range: {range_val:.2f}")
print(f"Percentiles (25th, 50th, 75th): {percentiles}")
print(f"IQR: {IQR:.2f}")

Thống kê dữ liệu COVID:
Mean: 7365292.35
Median: 63653.00
Mode: 0.00
Variance: 2004868898612282.75
Standard Deviation: 44775762.40
Range: 775866783.00
Percentiles (25th, 50th, 75th): [  6280.75  63653.   758272.  ]
IQR: 751991.25

In [22]:
vn = df[df['location'] == 'Vietnam']['total_cases'].dropna()

print("Số lượng dữ liệu Việt Nam:", len(vn))
print("Mean:", np.mean(vn))
print("Median:", np.median(vn))
print("Std:", np.std(vn))
print("IQR:", np.percentile(vn, 75) - np.percentile(vn, 25))

Số lượng dữ liệu Việt Nam: 1674
Mean: 6122353.316009558
Median: 10432547.0
Std: 5522634.483742673
IQR: 11615114.0

# KẾT THÚC